language: php
php:
  - 5.5
  - 5.6
  - hhvm

install:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php vendor/bin/phpunit -c .

after_script:
  - php vendor/bin/coveralls

notifications:
  email:
    - maa@scandesigns.dk